.. _variable_copy_wrapper__FUNCTION_FALLTHROUGH_ERROR:

Variable copy_wrapper::FUNCTION_FALLTHROUGH_ERROR
=================================================

- Defined in :ref:`file__Users_robkunkle_fork_goodlux_pytorch_aten_src_ATen_copy_wrapper.py`


Variable Documentation
----------------------


.. doxygenvariable:: copy_wrapper::FUNCTION_FALLTHROUGH_ERROR
